import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212]`}>
        <ClerkProvider>
          {/* We make the header absolute so it floats OVER the children (the canvas).
              pointer-events-none ensures you can click/draw "through" the empty space.
          */}
          <header className="absolute top-0 left-0 w-full flex justify-end items-center p-6 gap-4 h-16 z-50 pointer-events-none">
            <div className="pointer-events-auto">
              <Show when="signed-out">
                <div className="flex gap-4">
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-10 px-5 cursor-pointer shadow-lg">
                      Sign Up
                    </button>
                  </SignUpButton>
                </div>
              </Show>
              <Show when="signed-in">
                {/* Adding a subtle glow to the user button to make it pop against the canvas */}
                <div className="rounded-full border border-white/10 shadow-xl">
                  <UserButton 
                    appearance={{
                      elements: {
                        userButtonAvatarBox: "w-10 h-10"
                      }
                    }}
                  />
                </div>
              </Show>
            </div>
          </header>

          <main className="h-screen w-screen">
            {children}
          </main>
        </ClerkProvider>
      </body>
    </html>
  )
}